"""empty message

Revision ID: 6a0b02ad55f0
Revises: 
Create Date: 2021-05-03 23:09:58.741903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a0b02ad55f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mall',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=True),
    sa.Column('City', sa.String(length=100), nullable=True),
    sa.Column('District', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Name')
    )
    op.create_table('shop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Type', sa.String(length=140), nullable=True),
    sa.Column('Name', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Name')
    )
    op.create_table('shops_malls',
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('mall_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mall_id'], ['mall.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ondelete='SET NULL')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shops_malls')
    op.drop_table('shop')
    op.drop_table('mall')
    # ### end Alembic commands ###
