"""empty message

Revision ID: 69e396359f72
Revises: e83d6e81801c
Create Date: 2021-04-27 03:59:33.911934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69e396359f72'
down_revision = 'e83d6e81801c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('mall_City_key', 'mall', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('mall_City_key', 'mall', ['City'])
    # ### end Alembic commands ###
