"""empty message

Revision ID: 9432547311f5
Revises: 9e87ffbf61d8
Create Date: 2021-04-27 04:43:23.032689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9432547311f5'
down_revision = '9e87ffbf61d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('shops_malls_mall_id_fkey', 'shops_malls', type_='foreignkey')
    op.drop_constraint('shops_malls_shop_id_fkey', 'shops_malls', type_='foreignkey')
    op.create_foreign_key(None, 'shops_malls', 'mall', ['mall_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'shops_malls', 'shop', ['shop_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shops_malls', type_='foreignkey')
    op.drop_constraint(None, 'shops_malls', type_='foreignkey')
    op.create_foreign_key('shops_malls_shop_id_fkey', 'shops_malls', 'shop', ['shop_id'], ['id'])
    op.create_foreign_key('shops_malls_mall_id_fkey', 'shops_malls', 'mall', ['mall_id'], ['id'])
    # ### end Alembic commands ###
