"""empty message

Revision ID: 9e87ffbf61d8
Revises: b32b007ad552
Create Date: 2021-04-27 04:39:57.054609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e87ffbf61d8'
down_revision = 'b32b007ad552'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'mall', ['Name'])
    op.create_unique_constraint(None, 'shop', ['Name'])
    op.drop_constraint('shops_malls_mall_id_fkey', 'shops_malls', type_='foreignkey')
    op.drop_constraint('shops_malls_shop_id_fkey', 'shops_malls', type_='foreignkey')
    op.create_foreign_key(None, 'shops_malls', 'mall', ['mall_id'], ['id'])
    op.create_foreign_key(None, 'shops_malls', 'shop', ['shop_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shops_malls', type_='foreignkey')
    op.drop_constraint(None, 'shops_malls', type_='foreignkey')
    op.create_foreign_key('shops_malls_shop_id_fkey', 'shops_malls', 'shop', ['shop_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('shops_malls_mall_id_fkey', 'shops_malls', 'mall', ['mall_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'shop', type_='unique')
    op.drop_constraint(None, 'mall', type_='unique')
    # ### end Alembic commands ###
