"""empty message

Revision ID: a40c2e3028d9
Revises: 
Create Date: 2021-04-27 03:31:38.447951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a40c2e3028d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shops_malls',
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('mall_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mall_id'], ['mall.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], )
    )
    op.drop_table('post_tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_tags',
    sa.Column('shop_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mall_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['mall_id'], ['mall.id'], name='post_tags_mall_id_fkey'),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], name='post_tags_shop_id_fkey')
    )
    op.drop_table('shops_malls')
    # ### end Alembic commands ###
