"""empty message

Revision ID: b32b007ad552
Revises: 69e396359f72
Create Date: 2021-04-27 04:32:01.875920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b32b007ad552'
down_revision = '69e396359f72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('mall_Name_key', 'mall', type_='unique')
    op.drop_constraint('shop_Name_key', 'shop', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('shop_Name_key', 'shop', ['Name'])
    op.create_unique_constraint('mall_Name_key', 'mall', ['Name'])
    # ### end Alembic commands ###
