"""empty message

Revision ID: e83d6e81801c
Revises: 411fd1c78226
Create Date: 2021-04-27 03:50:32.032154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e83d6e81801c'
down_revision = '411fd1c78226'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'mall', ['Name'])
    op.create_unique_constraint(None, 'mall', ['City'])
    op.create_unique_constraint(None, 'shop', ['Name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shop', type_='unique')
    op.drop_constraint(None, 'mall', type_='unique')
    op.drop_constraint(None, 'mall', type_='unique')
    # ### end Alembic commands ###
